# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Dono' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dono
  pod 'DonoCore', :git => "https://github.com/dono-app/dono-pod/"
  pod 'KeychainSwift', '~> 3.0.16'
  pod 'SwiftHEXColors', '~> 1.0.4'
  pod 'SwiftyUserDefaults', '~> 2.2.0'


  target 'DonoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DonoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
