# Uncomment this line to define a global platform for your project
platform :osx, '10.11'

target 'Dono' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dono
  pod 'DonoCore', :git => "https://github.com/dono-app/dono-pod/"
  pod 'KeychainSwift', '~> 6.0'
  pod 'RFOverlayScrollView', '~> 0.3'
  pod 'SwiftHEXColors', '~> 1.0'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'SwiftyUserDefaults', '~> 3.0'
  pod 'SwiftyJSON'

  target 'DonoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DonoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3'
    end
  end
end
